### ISSUE TITLE
setup : Cannot build msvcr library: "msvcr90d.dll" not found

### ISSUE THREAD

**Issue by WUhailing** [ChadFulton/pymar#3]
Hi,

 The msg 'Cannot build msvcr library: "msvcr90d.dll" not found' occurs when line 'python setup.py build_ext --inplace' in compiled in cmd. Details are as follows,

Compiling hamilton_filter.pyx because it changed.
[1/1] Cythonizing hamilton_filter.pyx
running build_ext
Looking for python27.dll
Cannot build msvcr library: "msvcr90d.dll" not found
building 'hamilton_filter' extension
C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

I use Anaconda 2 (statsmodels.__version__ = '0.6.1') on Win 10, 64bit version.  Any suggestions on how to fix this? Thx a lot.

Regards,
hailing

**Comment by WUhailing** [comment]
I download msvcr90d.dll and put it into system32 directory, new error shows up.
' File "C:\Users\asus_admin\Anaconda2\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 274, in generate_def
raise ValueError("Symbol table not found")
ValueError: Symbol table not found'

**Comment by ChadFulton** [comment]
This package (`pymar`) is not really supported anymore. All of its functionality has been incorporated into Statsmodels version 0.8.
