### ISSUE TITLE
Multiple Regimes

### ISSUE THREAD

**Issue by sursu** [ChadFulton/pymar#4]
I looked briefly at the code. Is it the .py version of the .ipynb [here](https://www.statsmodels.org/dev/examples/notebooks/generated/markov_autoregression.html)?

How would an implementation with multiple regimes look like?

**Comment by ChadFulton** [comment]
> I looked briefly at the code. Is it the .py version of the .ipynb here?

The functionality of the `pymar` package has been moved into https://github.com/statsmodels/statsmodels, which is what the notebook you linked to uses.

> How would an implementation with multiple regimes look like?

I'm not sure what you mean - for example, the notebook you linked to gives an example of a model with multiple regimes.

**Comment by sursu** [comment]
Didn't see it at first look.
Thanks!
